
default:
  image: dockerhub.devops.telekom.de/bellsoft/liberica-openjdk-alpine:21
  tags:
    - otc_run_sysbox_s

stages:
  - build
  - test
  - deploy

variables:
  MAVEN_OPTS: >-
      -Duser.home=${CI_PROJECT_DIR}
      -Dhttp.proxyHost=proxy.devops.telekom.de
      -Dhttp.proxyPort=3128
      -Dhttps.proxyHost=proxy.devops.telekom.de
      -Dhttps.proxyPort=3128

cache:
  paths:
    - $CI_PROJECT_DIR/.m2/repository

build:
  stage: build
  script:
    - ./mvnw compile -s .mvn/settings.xml

deploy:
  stage: deploy
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  services:
    - name: 'dockerhub.devops.telekom.de/docker:20.10.12-dind'
      alias: docker
      command: ['--tls=false', '--host=tcp://0.0.0.0:2375', '--registry-mirror=https://dockerhub.devops.telekom.de']
  before_script:
    - apk add docker
  script:
    - echo "Building all modules"
    - ./mvnw clean install -s .mvn/settings.xml -DskipTests
    - echo "Login to docker"
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - echo "Building Docker image"
    - ./mvnw -pl chatbot-openai-code-migration-app spring-boot:build-image -DimageName=$CI_REGISTRY_IMAGE -DimageTag=$CI_COMMIT_REF_SLUG -s .mvn/settings.xml -DskipTests
    - echo "Pushing Docker Image to Container Registry of the project"
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  only:
    - tags

test:
  stage: test
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  services:
    - name: 'dockerhub.devops.telekom.de/docker:20.10.12-dind'
      command: ['--tls=false', '--host=tcp://0.0.0.0:2375', '--registry-mirror=https://dockerhub.devops.telekom.de']
      alias: docker
  script:
    - echo "Running tests"
    - ./mvnw test -s .mvn/settings.xml